# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
APPNAME := conv2d

ENABLE_AMU ?= 0
EXTRA_CFLAGS += -DENABLE_AMU=$(ENABLE_AMU)

include $(DRIVERS)/common_bare.mk
