# TODO: read HLS configuration from device registers instead
EXTRA_CFLAGS ?= -DFIR_FX_WIDTH=32
APPNAME := fir

#$(info $$DRIVERS  is [${DRIVERS}])
#$(info $$FIR_FX_WIDTH  is [${FIR_FX_WIDTH}])
include $(DRIVERS)/common.mk
